### ISSUE TITLE
Windows Installation Instructions Incorrect?

### ISSUE THREAD

**Issue by ingalless** [17cupsofcoffee/tetra-www#2]
Hi! Thanks for Tetra

I found that to get my game to compile with Tetra I needed to copy the .dll from the SDL2 Windows. I'll submit a pull request to the docs 👍

**Comment by 17cupsofcoffee** [comment]
As discussed on #3, this isn't required, but I will leave this issue open as a reminder for me to improve that section of the docs 🙂

**Comment by 17cupsofcoffee** [comment]
Done in https://github.com/17cupsofcoffee/tetra-www/commit/799e43bd71a30b5c91bf758a884b6078ef9bb7dc.
